import path from "node:path";
import { copyFile, writeFile } from "node:fs/promises";
import { ensureWorkspace, workspace } from "./config.mjs";
import { getKnowledgeFile, writeSourceManifest } from "./store.mjs";
import { fetchSeedMetadata, renderNormalizedSections } from "./source-analysis.mjs";
import { hashContent, relative, slugify, titleFromFile } from "./utils.mjs";

export async function ingestSource({
  title,
  sourceType,
  content,
  tags = [],
  sourcePath,
  qualityScore = null,
  qualityBreakdown = null,
  sourceSummary = null,
}) {
  await ensureWorkspace();
  const importedPath = typeof sourcePath === "string" ? sourcePath.trim() : "";
  const importedFileName = importedPath ? path.basename(importedPath) : "";
  const importedExt = importedFileName ? path.extname(importedFileName) || ".md" : ".md";
  const safeTitle = title?.trim() || (importedFileName ? titleFromFile(importedFileName) : "Untitled Source");
  const fileName = `${slugify(safeTitle)}${importedPath ? importedExt : ".md"}`;
  const filePath = path.join(workspace.raw, fileName);
  const now = new Date().toISOString();
  let importMode = "inline";

  if (importedPath) {
    await copyFile(path.resolve(importedPath), filePath);
    importMode = "file";
  } else {
    const markdown = `# ${safeTitle}\n\n## Source Type\n${sourceType}\n\n## Notes\n${content?.trim() || "No source content provided yet."}\n`;
    await writeFile(filePath, markdown, "utf8");
  }

  const fileRecord = await getKnowledgeFile("source", fileName);
  const manifest = {
    id: fileName,
    title: safeTitle,
    sourceType,
    path: relative(filePath),
    tags,
    ingestedAt: now,
    importMode,
    originalPath: importedPath || null,
    parsedPath: null,
    parsedBlocksPath: null,
    summaryPath: null,
    conceptSlugs: [],
    compileStats: null,
    compiledAt: null,
    qualityScore,
    qualityBreakdown: qualityBreakdown ?? (qualityScore === null ? null : { totalScore: qualityScore }),
    sourceSummary: sourceSummary || (fileRecord ? fileRecord.excerpt : ""),
    contentHash: hashContent(fileRecord ? fileRecord.content : ""),
  };
  await writeSourceManifest(fileName, manifest);
  return manifest;
}

export async function createResearchSource(payload, timestamp) {
  const topic = payload.topic?.trim() || "Untitled Research Topic";
  const notes = payload.notes?.trim() || "No analyst notes were provided.";
  const seedSources = Array.isArray(payload.seedSources) ? payload.seedSources.filter(Boolean) : [];
  const fetchedSeeds = [];
  for (const seed of seedSources) {
    try {
      fetchedSeeds.push(await fetchSeedMetadata(seed));
    } catch (error) {
      fetchedSeeds.push({
        url: seed,
        kind: "web-article",
        host: "unreachable",
        title: seed,
        description: error instanceof Error ? error.message : String(error),
        status: 0,
        contentType: "unreachable",
      });
    }
  }
  const rankedSeeds = [...fetchedSeeds].sort((left, right) => (right.qualityScore ?? 0) - (left.qualityScore ?? 0) || left.title.localeCompare(right.title));
  const content = `# ${topic}

## Research Brief
This source was generated by the research job as a topic starter for the wiki.

## Hypothesis
${notes}

## Seed Sources
${rankedSeeds.length
    ? rankedSeeds.map((item) => "- " + item.title + " (" + item.kind + ", quality " + (item.qualityScore ?? 0) + "/100) from " + item.url + (item.owner && item.repo ? " [" + item.owner + "/" + item.repo + "]" : "") + ": " + (item.readmeSummary || item.extractedSummary || item.description)).join("\n")
    : "- No external seed sources were provided."}

## Findings
- ${topic} should become a dedicated topic wiki page.
- The compile step should merge this research note with related concepts and contradictions.
- Follow-up work can refine this into a deeper multi-source investigation.

## Quality Ranking
${rankedSeeds.length
    ? rankedSeeds.map((item) => `- ${item.title}: depth ${item.qualityBreakdown?.contentDepth ?? 0}, structure ${item.qualityBreakdown?.structureQuality ?? 0}, authority ${item.qualityBreakdown?.sourceAuthority ?? 0}, evidence ${item.qualityBreakdown?.evidenceDensity ?? 0}`).join("\n")
    : "- No ranked seed sources yet."}
`;

  const primarySource = await ingestSource({
    title: `${topic} Research`,
    sourceType: "research-note",
    content,
    tags: [topic, "research"],
    sourcePath: "",
  });

  const harvestedSources = [];
  for (const item of fetchedSeeds) {
    harvestedSources.push(await ingestSource({
      title: item.title,
      sourceType: item.kind,
      content: `URL: ${item.url}

Host: ${item.host}

Description: ${item.description}

Status: ${item.status}

Content-Type: ${item.contentType}

Quality Score: ${item.qualityScore ?? 0}/100

Body Word Count: ${item.bodyWordCount ?? 0}${item.owner && item.repo ? "\n\nRepository: " + item.owner + "/" + item.repo : ""}

## Source Summary
${item.readmeSummary || item.extractedSummary || item.description}

## Extracted Body
${item.extractedSummary || "No body summary extracted."}${item.readmeSummary ? "\n\n## README Summary\n" + item.readmeSummary : ""}

${renderNormalizedSections(item) || "## Normalized Source\n- No normalized sections extracted yet."}`,
      tags: [topic, item.kind, item.host, item.owner && item.repo ? `${item.owner}/${item.repo}` : ""].filter(Boolean),
      sourcePath: "",
      qualityScore: item.qualityScore ?? null,
      qualityBreakdown: item.qualityBreakdown ?? null,
      sourceSummary: item.readmeSummary || item.extractedSummary || item.description,
    }));
  }

  return { primarySource, harvestedSources, fetchedSeeds };
}
